name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

  workflow_dispatch:  # Allows manual trigger

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the repository
        with:
          persist-credentials: false  # Prevent permission issues

      - name: Set Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: AshishRogannagari  # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Change File Permissions
        run: |
          chmod +x dist/github-contribution-grid-snake.svg
          mv dist/github-contribution-grid-snake.svg .

      - uses: actions/upload-artifact@v4
        with:
          name: snake-artifact
          path: github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git checkout -B output
          git add github-contribution-grid-snake.svg
          git commit -m "Update Snake Animation"
          git push -f origin output
