name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

  workflow_dispatch:  # Allows manual trigger

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: AshishRogannagari  # Your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v4
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg

      - uses: actions/checkout@v4

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -B output
          mv dist/github-contribution-grid-snake.svg ./
          git add github-contribution-grid-snake.svg
          git commit -m "Update Snake Animation"
          git push -f origin output
